
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Win10
 */
public class calculate extends javax.swing.JFrame {

    /**
     * Creates new form calculate
     */
    double firstnum,secondnum,result;
    String operations,s="";
    
    
    public calculate() {
        initComponents();
    }
void keyinput(){
    new Timer(0,new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
           
        }
    }).start();


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enter = new javax.swing.JTextField();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        ce = new javax.swing.JButton();
        percent = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        backspace = new javax.swing.JButton();
        c = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        bracketopen = new javax.swing.JButton();
        squareroot = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        bracketclose = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        factorial = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        exponent = new javax.swing.JButton();
        ln = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        mod = new javax.swing.JButton();
        display = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enter.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 600, 50));

        btn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        btn7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn7KeyPressed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 285, 58, 52));

        btn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        btn8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn8KeyPressed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 285, 58, 52));

        btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        btn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn1KeyPressed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 415, 58, 52));

        btn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        btn9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn9KeyPressed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 285, 58, 52));

        btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        btn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn2KeyPressed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 415, 58, 52));

        btn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        btn4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn4KeyPressed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 350, 58, 52));

        btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        btn3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn3KeyPressed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 415, 58, 52));

        btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        btn6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn6KeyPressed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 350, 58, 52));

        btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        btn5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn5KeyPressed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 350, 58, 52));

        multiply.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        multiply.setText("X");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });
        multiply.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                multiplyKeyPressed(evt);
            }
        });
        getContentPane().add(multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 285, 57, 52));

        minus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        minus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                minusKeyPressed(evt);
            }
        });
        getContentPane().add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 415, 58, 52));

        ce.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ce.setText("CE");
        ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceActionPerformed(evt);
            }
        });
        getContentPane().add(ce, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 220, 58, 52));

        percent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        percent.setText("%");
        getContentPane().add(percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 480, 58, 52));

        divide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        divide.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                divideKeyPressed(evt);
            }
        });
        getContentPane().add(divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 220, 58, 52));

        btn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        btn0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn0KeyPressed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 480, 58, 52));

        backspace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backspace.setText("<x");
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });
        getContentPane().add(backspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 220, 58, 52));

        c.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c.setText("C");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 220, 58, 52));

        plus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        plus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                plusKeyPressed(evt);
            }
        });
        getContentPane().add(plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 350, 58, 52));

        decimal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        decimal.setText(".");
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });
        getContentPane().add(decimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 480, 58, 52));

        equal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        getContentPane().add(equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 480, 58, 52));

        btn10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn10.setText("5");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 285, 58, 52));

        bracketopen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bracketopen.setText("(");
        bracketopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracketopenActionPerformed(evt);
            }
        });
        getContentPane().add(bracketopen, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 415, 58, 52));

        squareroot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        squareroot.setText("√ ");
        squareroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squarerootActionPerformed(evt);
            }
        });
        getContentPane().add(squareroot, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 350, 58, 52));

        btn11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn11.setText("0");
        getContentPane().add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 415, 58, 52));

        sin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        getContentPane().add(sin, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 220, 87, 52));

        c1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c1.setText("C");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 220, 58, 52));

        bracketclose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bracketclose.setText(")");
        bracketclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracketcloseActionPerformed(evt);
            }
        });
        getContentPane().add(bracketclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 480, 58, 52));

        btn13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn13.setText("8");
        getContentPane().add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 285, 58, 52));

        factorial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        factorial.setText("!");
        factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialActionPerformed(evt);
            }
        });
        getContentPane().add(factorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 285, 58, 52));

        cos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });
        getContentPane().add(cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 285, 87, 52));

        btn16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn16.setText("2");
        getContentPane().add(btn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 350, 58, 52));

        exponent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exponent.setText("^");
        exponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exponentActionPerformed(evt);
            }
        });
        getContentPane().add(exponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 220, 58, 52));

        ln.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ln.setText("ln");
        getContentPane().add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 415, 87, 52));

        tan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        getContentPane().add(tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 350, 87, 52));

        mod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mod.setText("mod");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });
        getContentPane().add(mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 480, 87, 52));

        display.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 600, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        display.setText(display.getText()+4);
       enter.setText(enter.getText()+4);
       s=s+4;
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
       display.setText(display.getText()+5);
       enter.setText(enter.getText()+5);
       s=s+5;
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
     display.setText(display.getText()+6);
     enter.setText(enter.getText()+6);
     s=s+6;   
    }//GEN-LAST:event_btn6ActionPerformed

    private void ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceActionPerformed
       
        int le,ld;
        ld=display.getText().length();
        le=enter.getText().length();
        display.setText(display.getText().substring(0, ld-le));
        enter.setText("");
    }//GEN-LAST:event_ceActionPerformed

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        String sdisplay,senter;
        int le,ld;
        le=enter.getText().length();
        ld=display.getText().length();
        senter=enter.getText().substring(0,le-1);
        sdisplay=display.getText().substring(0,ld-1);
        enter.setText(senter);
        display.setText(sdisplay);
    }//GEN-LAST:event_backspaceActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
       enter.setText("");
       display.setText("");
    }//GEN-LAST:event_cActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
       display.setText(display.getText()+".");
       enter.setText(enter.getText()+".");
       s=s+".";
    }//GEN-LAST:event_decimalActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10ActionPerformed

    private void bracketopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bracketopenActionPerformed
      display.setText(display.getText()+"(");
       enter.setText(enter.getText()+"(");
       s=s+"(";
    }//GEN-LAST:event_bracketopenActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
            display.setText("sin("+display.getText()+")");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="sin";
    }//GEN-LAST:event_sinActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        
    }//GEN-LAST:event_c1ActionPerformed

    private void exponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exponentActionPerformed
            display.setText(display.getText()+"^");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="^";
            s=s+"^";
    }//GEN-LAST:event_exponentActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
            display.setText("tan("+display.getText()+")");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="tan";
    }//GEN-LAST:event_tanActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
       
    }//GEN-LAST:event_modActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
            display.setText(display.getText()+"+");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="+";
            s=s+"+";           
    }//GEN-LAST:event_plusActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
       display.setText(display.getText()+1);
       enter.setText(enter.getText()+1);
       s=s+"1";
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        display.setText(display.getText()+2);
       enter.setText(enter.getText()+2);
       s=s+"2";
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
         display.setText(display.getText()+3);
       enter.setText(enter.getText()+3);
       s=s+"3";
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        display.setText(display.getText()+7);
       enter.setText(enter.getText()+7);
       s=s+"7";
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
       display.setText(display.getText()+8);
       enter.setText(enter.getText()+8);
       s=s+"8";
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
       display.setText(display.getText()+9);
       enter.setText(enter.getText()+9);
       s=s+"9";
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        display.setText(display.getText()+0);
       enter.setText(enter.getText()+0);
       s=s+"0";
    }//GEN-LAST:event_btn0ActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
            display.setText(display.getText()+"/");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="/";
            s=s+"/";
    }//GEN-LAST:event_divideActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
            display.setText(display.getText()+"X");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="X";
            s=s+"x";
    }//GEN-LAST:event_multiplyActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
            display.setText(display.getText()+"-");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="-";
            s=s+"-";
    }//GEN-LAST:event_minusActionPerformed

    private void bracketcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bracketcloseActionPerformed
        display.setText(display.getText()+")");
       enter.setText(enter.getText()+")");
       s=s+")";
    }//GEN-LAST:event_bracketcloseActionPerformed

    private void squarerootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squarerootActionPerformed
            display.setText("√ ("+display.getText()+")");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="root";
            s=s+"√";
    }//GEN-LAST:event_squarerootActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
     System.out.print(s);
       if ("c".equals(operations))
            display.setText("");
        if ("+".equals(operations))
        {
            secondnum=Double.parseDouble(enter.getText());
            result=firstnum+secondnum;
        }
        if ("-".equals(operations))
        {
            secondnum=Double.parseDouble(enter.getText());
            result =firstnum-secondnum;
        }
        if (operations == "X")
        {
            secondnum=Double.parseDouble(enter.getText());
            result =firstnum*secondnum;
        }     
        if ("/".equals(operations))
        {
            secondnum=Double.parseDouble(enter.getText());
            result =firstnum/secondnum;
        }
        if ("^".equals(operations))
        {
            secondnum=Double.parseDouble(enter.getText());
            result =Math.pow(firstnum,secondnum);
        }
        if ("root".equals(operations))
            result=Math.pow(firstnum, 0.5);
        if ("cos".equals(operations))
            result=Math.cos(firstnum);
        if ("sin".equals(operations))
            result=Math.sin(firstnum);
        if ("tan".equals(operations))
            result=Math.tan(firstnum);
        if ("!".equals(operations))
        {
            int i,m=1,inum;
            inum=(int)firstnum;
            for (i=1;i<=inum;i++)
                m=m*i;
            result=m;
        }
       enter.setText(result+"");
      
    }//GEN-LAST:event_equalActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
            display.setText("cos("+display.getText()+")");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="cos";
    }//GEN-LAST:event_cosActionPerformed

    private void factorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialActionPerformed
            display.setText(display.getText()+"!");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="!";
            s=s+"!";
            
    }//GEN-LAST:event_factorialActionPerformed

    private void btn9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn9KeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_9){display.setText(display.getText()+9);
       enter.setText(enter.getText()+9);}// TODO add your handling code here:
    }//GEN-LAST:event_btn9KeyPressed

    private void btn8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn8KeyPressed
     int keycode=evt.getKeyCode();
if (keycode==evt.VK_8){display.setText(display.getText()+8);
       enter.setText(enter.getText()+8);}   // TODO add your handling code here:
    }//GEN-LAST:event_btn8KeyPressed

    private void btn7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn7KeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_7){display.setText(display.getText()+7);
       enter.setText(enter.getText()+7);}        // TODO add your handling code here:
    }//GEN-LAST:event_btn7KeyPressed

    private void btn4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn4KeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_4){display.setText(display.getText()+4);
       enter.setText(enter.getText()+4);}        // TODO add your handling code here:
    }//GEN-LAST:event_btn4KeyPressed

    private void btn5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn5KeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_5){display.setText(display.getText()+5);
       enter.setText(enter.getText()+5);}        // TODO add your handling code here:
    }//GEN-LAST:event_btn5KeyPressed

    private void btn6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn6KeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_6){display.setText(display.getText()+6);
       enter.setText(enter.getText()+6);}        // TODO add your handling code here:
    }//GEN-LAST:event_btn6KeyPressed

    private void btn1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn1KeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_1){display.setText(display.getText()+1);
       enter.setText(enter.getText()+1);}        // TODO add your handling code here:
    }//GEN-LAST:event_btn1KeyPressed

    private void btn2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn2KeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_2){display.setText(display.getText()+2);
       enter.setText(enter.getText()+2);}        // TODO add your handling code here:
    }//GEN-LAST:event_btn2KeyPressed

    private void btn3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn3KeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_3){display.setText(display.getText()+3);
       enter.setText(enter.getText()+3);}        // TODO add your handling code here:
    }//GEN-LAST:event_btn3KeyPressed

    private void btn0KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn0KeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_0){display.setText(display.getText()+0);
       enter.setText(enter.getText()+0);}        // TODO add your handling code here:
    }//GEN-LAST:event_btn0KeyPressed

    private void plusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plusKeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_ADD){ display.setText(display.getText()+"+");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="+";}        // TODO add your handling code here:
    }//GEN-LAST:event_plusKeyPressed

    private void minusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minusKeyPressed
 int keycode=evt.getKeyCode();
if (keycode==evt.VK_MINUS){ display.setText(display.getText()+"-");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="-";}        // TODO add your handling code here:
    }//GEN-LAST:event_minusKeyPressed

    private void multiplyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_multiplyKeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_MULTIPLY){ display.setText(display.getText()+"*");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="*";}         // TODO add your handling code here:
    }//GEN-LAST:event_multiplyKeyPressed

    private void divideKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_divideKeyPressed
int keycode=evt.getKeyCode();
if (keycode==evt.VK_DIVIDE){ display.setText(display.getText()+"/");   
            firstnum=Double.parseDouble(enter.getText());
            enter.setText("");
            operations="/";}         // TODO add your handling code here:
    }//GEN-LAST:event_divideKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int ecode=evt.getKeyCode();
        if (ecode==evt.VK_0)
            {
             display.setText(display.getText()+0);
             enter.setText(enter.getText()+0);
            }
        if (ecode==evt.VK_1)
            {
             display.setText(display.getText()+0);
             enter.setText(enter.getText()+0);
            }
        if (ecode==evt.VK_2)
            {
             display.setText(display.getText()+0);
             enter.setText(enter.getText()+0);
            }
        if (ecode==evt.VK_3)
            {
             display.setText(display.getText()+0);
             enter.setText(enter.getText()+0);
            }
        if (ecode==evt.VK_4)
            {
             display.setText(display.getText()+0);
             enter.setText(enter.getText()+0);
            }
        if (ecode==evt.VK_5)
            {
             display.setText(display.getText()+0);
             enter.setText(enter.getText()+0);
            }
        if (ecode==evt.VK_6)
            {
             display.setText(display.getText()+0);
             enter.setText(enter.getText()+0);
            }
        if (ecode==evt.VK_7)
            {
             display.setText(display.getText()+0);
             enter.setText(enter.getText()+0);
            }
        if (ecode==evt.VK_8)
            {
             display.setText(display.getText()+0);
             enter.setText(enter.getText()+0);
            }
         if (ecode==evt.VK_9)
            {
             display.setText(display.getText()+9);
             enter.setText(enter.getText()+9);
            }
        
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backspace;
    private javax.swing.JButton bracketclose;
    private javax.swing.JButton bracketopen;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton c;
    private javax.swing.JButton c1;
    private javax.swing.JButton ce;
    private javax.swing.JButton cos;
    private javax.swing.JButton decimal;
    private javax.swing.JTextField display;
    private javax.swing.JButton divide;
    private javax.swing.JTextField enter;
    private javax.swing.JButton equal;
    private javax.swing.JButton exponent;
    private javax.swing.JButton factorial;
    private javax.swing.JButton ln;
    private javax.swing.JButton minus;
    private javax.swing.JButton mod;
    private javax.swing.JButton multiply;
    private javax.swing.JButton percent;
    private javax.swing.JButton plus;
    private javax.swing.JButton sin;
    private javax.swing.JButton squareroot;
    private javax.swing.JButton tan;
    // End of variables declaration//GEN-END:variables

    
}
